name: "RSync"
description: ""
author: "Peter Kracik"
inputs:
  privateKey:
    description: "Private key"
    require: false
    default: ""
  command:
    description: "rsync command(s) to execute"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "gray-dark"
  icon: "terminal"
